### ISSUE TITLE
[BlueBubbles] Implement Delivery Receipts

### ISSUE THREAD

**Issue by joshuafhiggins** [mautrix/imessage#202]
Currently, the bridge only reflects when a message is sent and read. This would be a nice feature to have and I may implement it if I have the time but it should be easy to do with other message updates. I was unaware the bridge wasn't doing this until I started using the new Beeper beta app and checked back with the original.

**Comment by trek-boldly-go** [comment]
It's not ideal because it is hard coded, but it does actually report that messages are delivered. 
https://github.com/mautrix/imessage/blob/master/imessage%2Fbluebubbles%2Fapi.go#L1465

I'm only okay with the hard coded value because this conversion function would only ever run if the message is actually delivered.

**Comment by trek-boldly-go** [comment]
Ah sorry, sent is the hard coded one. But it is still sending delivery receipts as far as I can tell.

**Comment by joshuafhiggins** [comment]
That's strange, do you see delivery receipts in your UI?

**Comment by joshuafhiggins** [comment]
Resolved with [5a967bd](https://github.com/mautrix/imessage/pull/200/commits/5a967bd17788dde14a4b37ad6bd7d4af373b58b1)
